### ISSUE TITLE
ctrl+c causes interswitch links to be toggled

### ISSUE THREAD

**Issue by ldev** [tech-server/gondul#100]
ctrl+c on the switch information overlay causes the links between switches to be toggled

**Comment by KristianLyng** [comment]
Same issue as #72 , more or less...

**Comment by KristianLyng** [comment]
Closing this because honestly, I'm not sure it's relevant anymore. We need to actually _have_ inter-switch links for this to be tested, and we haven't really utilized it recently. And that's a different problem...
