### ISSUE TITLE
Ønskeliste for hva Gondul skal gi ut av data for å ta over planning sine tekstfiner sin funksjonalitet for ekstern behandling

### ISSUE THREAD

**Issue by ldev** [tech-server/gondul#110]
Kryptisk tittel er kryptisk.
---

Kilder:
    https://github.com/tech-server/tgmanage/tree/master/examples/tg16
        netlist.txt
        patchlist.txt
        switches.txt

syntax:
    switches.txt: e1-3 88.92.0.0/26 2a06:5840:0a::/64 88.92.54.2/26 2a06:5840:54a::2/64 1013 distro0
    patchlist.txt: e1-4 distro0 ge-0/0/1 ge-1/0/1 ge-2/0/1
    netlist.txt: 88.92.28.128/26 2a06:5840:28c::/64 e67-4

Ønsket output-format: JSON

Alternativer:
    sette/ikke sette distro i HTTP GET-requesten. Uten distro satt hentes strukturen for alle distroene

Eksempelstruktur, som dekker alt planning dekker i dag:

```
distro3:
    switches:
        e1-3 (switches.txt 1. kolonne, patchlist.txt 1. kolonne, netlist.txt 3. kolonne):
            uplinks_from_distro:
                ge-0/0/1 (patchlist.txt 3. kolonne)
                ge-1/0/1 (patchlist.txt 4. kolonne)
                ge-2/0/1 (patchlist.txt 5. kolonne)
            mgmt_v4:
                88.92.54.2/26 (switches.txt 4. kolonne)
            mgmt_v6
                2a06:5840:54a::2/64 (switches.txt 5. kolonne)
            client_subnet_v4
                88.92.0.0/26 (switches.txt 2. kolonne, netlist.txt 1. kolonne)
            client_subnet_v6
                2a06:5840:0a::/64 (switches.txt 3. kolonne, netlist.txt 2. kolonne)
            client_vlan
                1013 (switches.txt 6 kolonne)

        creativia-sw3:
            uplinks_from_distro
                [...]
```

**Comment by KristianLyng** [comment]
Dette blir fullstendig dekket av templating nå. switches.txt er på plass, patchlist.txt er på vei, sammen med netlist.txt.

Lar greia ligge til vi er i mål, men det kule nå er at vi kan lage hva vi vil egentlig. Og med vi mener jeg "alle som klarer å lese jinja2 dokumentasjonen".

**Comment by KristianLyng** [comment]
Jeg ombestemte meg. Jeg har lagd issues på alt som er relevant her. Derfor lukker jeg saken. Alt blir støtta.
